// flow-typed signature: 635c39d32fa021c11cf5b86ec248b3ff
// flow-typed version: <<STUB>>/d3-chord_v1.0.6/flow_v0.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-chord'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-chord' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-chord/dist/d3-chord' {
  declare module.exports: any;
}

declare module 'd3-chord/dist/d3-chord.min' {
  declare module.exports: any;
}

declare module 'd3-chord/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-chord/src/array' {
  declare module.exports: any;
}

declare module 'd3-chord/src/chord' {
  declare module.exports: any;
}

declare module 'd3-chord/src/constant' {
  declare module.exports: any;
}

declare module 'd3-chord/src/index' {
  declare module.exports: any;
}

declare module 'd3-chord/src/math' {
  declare module.exports: any;
}

declare module 'd3-chord/src/ribbon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-chord/dist/d3-chord.js' {
  declare module.exports: $Exports<'d3-chord/dist/d3-chord'>;
}
declare module 'd3-chord/dist/d3-chord.min.js' {
  declare module.exports: $Exports<'d3-chord/dist/d3-chord.min'>;
}
declare module 'd3-chord/rollup.config.js' {
  declare module.exports: $Exports<'d3-chord/rollup.config'>;
}
declare module 'd3-chord/src/array.js' {
  declare module.exports: $Exports<'d3-chord/src/array'>;
}
declare module 'd3-chord/src/chord.js' {
  declare module.exports: $Exports<'d3-chord/src/chord'>;
}
declare module 'd3-chord/src/constant.js' {
  declare module.exports: $Exports<'d3-chord/src/constant'>;
}
declare module 'd3-chord/src/index.js' {
  declare module.exports: $Exports<'d3-chord/src/index'>;
}
declare module 'd3-chord/src/math.js' {
  declare module.exports: $Exports<'d3-chord/src/math'>;
}
declare module 'd3-chord/src/ribbon.js' {
  declare module.exports: $Exports<'d3-chord/src/ribbon'>;
}
